# Generated by Django 4.2.5 on 2023-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_first_name_useraddress_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperaryOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('temp_otp', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Temperary OTP',
                'verbose_name_plural': 'Temperary OTP',
            },
        ),
    ]
