# Generated by Django 4.2.5 on 2023-09-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_wishlist_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='selling_price',
        ),
    ]
