# Generated by Django 4.2.5 on 2023-10-12 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review_reviewimages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_alter_cart_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=10)),
                ('paymentID', models.CharField(max_length=50)),
                ('ship_to_name', models.CharField(max_length=100)),
                ('ship_to_email', models.CharField(default='', max_length=100)),
                ('ship_to_phonenumber', models.CharField(max_length=10)),
                ('ship_to_address1', models.CharField(max_length=100)),
                ('ship_to_country', models.CharField(default='India', max_length=30)),
                ('ship_to_state', models.CharField(max_length=30)),
                ('ship_to_city', models.CharField(max_length=30)),
                ('ship_to_zip', models.CharField(max_length=6)),
                ('subtotal', models.IntegerField(default=0)),
                ('coupon_applied', models.CharField(default='XXXX', max_length=8)),
                ('coupon_discount', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('no_of_items', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='products.product')),
            ],
        ),
    ]
