# Generated by Django 4.2.5 on 2023-10-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type_details',
            field=models.TextField(null=True),
        ),
    ]
