# Generated by Django 4.2.5 on 2023-10-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_type_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(default='', max_length=5),
        ),
    ]
