# Generated by Django 4.2.5 on 2023-10-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderproduct_color_orderproduct_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charges',
            field=models.IntegerField(default=0),
        ),
    ]
