# Generated by Django 4.2.5 on 2023-10-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
