# Generated by Django 4.2.5 on 2023-10-13 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_review_reviewimages'),
        ('orders', '0009_remove_orderproduct_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=10)),
                ('paymentID', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(default='India', max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('address_line1', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('subtotal', models.IntegerField(default=0)),
                ('coupon_name', models.CharField(default='XXXX', max_length=8)),
                ('coupon_discount', models.IntegerField(default=0)),
                ('delivery_charges', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('no_of_items', models.IntegerField(default=0)),
                ('payment_type_details', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, verbose_name='Quantity')),
                ('size', models.CharField(default='', max_length=5)),
                ('color', models.CharField(default='', max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='products.product')),
            ],
        ),
    ]
