# Generated by Django 4.2.5 on 2023-10-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_name',
            field=models.CharField(default='XXXX', max_length=8, null=True),
        ),
    ]
