# Generated by Django 4.2.5 on 2023-10-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review_reviewimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Product Review', 'verbose_name_plural': 'Product Reviews'},
        ),
        migrations.AlterModelOptions(
            name='reviewimages',
            options={'verbose_name': 'Product Review', 'verbose_name_plural': 'Product Reviews'},
        ),
    ]
