# Generated by Django 4.2.5 on 2023-10-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_options_alter_reviewimages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewimages',
            options={'verbose_name': 'Product Review Images', 'verbose_name_plural': 'Product Review Images'},
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='products.product'),
        ),
    ]
